# Generated by Django 3.2.5 on 2022-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='presentcart',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
